### PR TITLE
encode html entitites

### LINKED ISSUE #10: `&` in the body leads to jmeter failure
Jmeter doesn't like some special symbols in the body like ampersands `&`.

```
body = list(title = "this & that", userId = 1)
```

leads to
```
XmlPullParserException: entity reference names can not start with character ' ' (position: START_TAG seen ...<stringProp name="Argument.value">{&quot;title&quot;:&quot;this & ... @34:83) 
```
one solution is to encode more HTML entities, instead of only `&quot;`. This is, in fact, what Jmeter itself does:
```
<stringProp name="Argument.value">{&quot;title&quot;:&quot;this &amp; that&quot;,&quot;userId&quot;:1}</stringProp>
```

Here's a sampler of Jmeter cares about:

**input:**  
```
 !@#$%^&*()-=+~`?/>.<,±§\'|:;{]{}äüãçöß]
```

**jmeter:**
```
 !@#$%^&amp;*()-=+~`?/&gt;.&lt;,±§\&apos;|:;{]{}äüãçöß]
```

### PR DESCRIPTION
**Pull request by jcpsantiago**
Fixes https://github.com/tmobile/loadtest/issues/10

### CODE REVIEW

File: R/loadtest.R [hunk 1]
```diff
@@ -60,6 +60,29 @@ parse_url <- function(url){
...
+#' @return a string
+#'
+#' @examples
+#' encode_html_entities('{"title":"this & that"}')
+encode_html_entities <- function(stringified_body) {
+  body_noamp <- gsub("&", "&amp;", stringified_body)
+  body_noquot <- gsub("\"", "&quot;", body_noamp)
+  body_nogt <- gsub(">", "&gt;", body_noquot)
+  body_nolt <- gsub("<", "&lt;", body_nogt)
+  body_noapos <- gsub("\'", "&apos;", body_nolt)
```
Comment (jcpsantiago) [inline R/loadtest.R:79]: I'm not a fan of overwriting variables e.g. `x <- x + 1` but maybe here it's ok. Let me know what you think and I'll change accordingly.
